packages:
  - tools/perspective-test
  - tools/perspective-scripts
  - tools/perspective-bench
  - packages/perspective-client
  - tools/perspective-esbuild-plugin
  - packages/perspective-viewer-datagrid
  - packages/perspective-viewer-d3fc
  - packages/perspective-viewer-openlayers
  - packages/perspective-workspace
  - packages/perspective-jupyterlab
  - packages/perspective-react
  - packages/perspective-cli
  - rust/generate-metadata
  - rust/perspective
  - rust/perspective-js
  - rust/perspective-viewer
  - rust/perspective-python
  - rust/perspective-server
  - examples/*
  - docs

catalog:
  '@d3fc/d3fc-chart': 5.1.9
  '@d3fc/d3fc-element': 6.2.0
  '@fontsource/roboto-mono': 4.5.10
  '@iarna/toml': 3.0.0
  '@jupyter-widgets/base': '>2 <5'
  '@jupyterlab/application': '>2 <5'
  '@jupyterlab/builder': ^4
  '@lumino/application': <3
  '@lumino/widgets': <3
  '@playwright/experimental-ct-react': '=1.52.0'
  '@playwright/test': '=1.52.0'
  '@prospective.co/procss': 0.1.17
  '@types/d3': ^7.4.3
  '@types/lodash': ^4.17.20
  '@types/node': '>=22'
  '@types/react': ^18
  '@types/react-dom': ^18
  '@types/stoppable': '>=1'
  '@types/ws': '>=8'
  '@zip.js/zip.js': ^2.7.54
  apache-arrow: 18.1.0
  arraybuffer-loader: '>=1.0.8 <2'
  auto-changelog: ^2.5.0
  chalk: '>=5'
  chroma-js: '>=3 <4'
  commander: '>=14 <15'
  copy-webpack-plugin: ~12
  css-loader: '>=7 <8'
  d3: ^7.9.0
  d3-array: '>=3'
  d3-color: '>=3.1'
  d3-selection: '>=3'
  d3-svg-legend: '>=2'
  d3fc: ^15.2.13
  dotenv: '>=17'
  esbuild: ^0.25.5
  express: '>=5 <6'
  express-ws: '>=5 <6'
  fs-extra: '>=11 <12'
  glob-gitignore: ^1.0.15
  gradient-parser: '>=1 <2'
  html-webpack-plugin: '>=5 <6'
  http-server: ^14.1.1
  husky: '>=9'
  inquirer: '>=12 <13'
  less: ^4.1.0
  lodash: ^4.17.20
  microtime: '>=3 <4'
  mkdirp: ^0.5.6
  moment: ^2.30.1
  npm-run-all: ^4.1.5
  octokit: ^1.8.1
  ol: ^5.3.2
  prettier: '>=3 <4'
  pro_self_extracting_wasm: 0.0.9
  puppeteer: '>=24'
  react: ^18
  react-dom: ^18
  regular-table: '=0.6.8'
  stoppable: '=1.1.0'
  style-loader: '>=4 < 5'
  superstore-arrow: 3.2.0
  tar: ^7.4.3
  tsx: ^4.20.3
  typedoc: ^0.28.7
  typescript: '>=5 <6'
  vite: '>=6 <7'
  webpack: 5.102.0
  webpack-cli: '>=5 <6'
  ws: ^8.17.0
  zx: '>=8 <9'
